[versions]
# Defalut
androidGradlePlugin = "8.1.2"
kotlin = "1.8.10"

# AndroidX
androidXCore = "1.9.0"
androidXLifeCycle = "2.6.1"
androidXAppcompat = "1.6.1"

#Compose
composeUi = "1.3.3"
activityCompose = "1.7.0"
composeMaterial3 = "1.1.2"
composeCompiler = "1.4.3"
composeNav = "2.5.3"

# Test
junit = "4.13.2"
androidXJunit = "1.1.5"
espresso = "3.5.1"
material = "1.10.0"
compose-bom = "2023.03.00"

# Library
orbit = "6.1.0"

[libraries]
# <--------------------[ AndroidX ]-------------------->
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidXCore" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifeCycle" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidXAppcompat" }

# <--------------------[ Compose ]-------------------->
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "composeUi" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "composeUi" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "composeUi" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "composeUi" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeUi" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "composeUi" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-nav = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNav" }

# <--------------------[ Test ]-------------------->
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

# <-------------------[orbit-mvi]------------------>
orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit" }
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit" }
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit" }


# <--- [ Define Dependeicies used in build-logic ] --->
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
compose = ["activity-compose", "compose-ui", "compose-ui-graphics",
    "compose-ui-tooling", "compose-ui-tooling-preview", "compose-ui-test-manifest",
    "compose-ui-test-manifest", "compose-ui-test-junit4", "compose-material3", "compose-nav"]
orbit = ["orbit-core", "orbit-viewmodel", "orbit-compose"]

