name: "Todo"
description: "해야할 것이 있나요??🤔"
body:

  - type: textarea
    attributes:
      label: Describe
      description: |
        [Description] 할일의 설명을 작성해주세요.
      placeholder: |
        회원가입 페이지를 퍼블리싱 합니다!